---
# Minimal Jekyll config for GitHub Pages
markdown: kramdown
permalink: pretty

# Title for the site
title: AZ-305 Solutions Architect
theme: minima
---

# Minima enables navigation bar and cleaner styling
